RedditAPI/force-app/main/default/objects/Reddit_Post__c/Reddit_Post__c.object-meta.xml
<CustomObject>
    <label>Reddit Post</label>
    <nameField>
        <label>Reddit Post Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reddit Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RedditAPI/force-app/main/default/objects/Reddit_Post__c/fields/Author_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Author_Full_Name__c</fullName>
    <label>Author Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

RedditAPI/force-app/main/default/objects/Reddit_Post__c/fields/Selftext__c.field-meta.xml
<CustomField>
    <fullName>Selftext__c</fullName>
    <label>Selftext</label>
    <type>TextArea</type>
</CustomField>

RedditAPI/force-app/main/default/classes/RedditDataTest.cls
public with sharing class RedditDataTest {

    public static List <Reddit_Post__c> generateRedditPostRecords(){

        List <Reddit_Post__c> newListReddit = new List <Reddit_Post__c>();

        for (Integer i = 1; i <= 80; i++) {

            Reddit_Post__c rp = new Reddit_Post__c();
            rp.Name = 'Post Name '+i;
            rp.Author__c = 'Author Name '+i;
            rp.Author_Full_Name__c = 'Author Full Name '+i;
            rp.Thumbnail__c = 'Thumbnail '+i;
            rp.Selftext__c = 'Selftext '+i;
            newListReddit.add(rp);

        }

        if (!newListReddit.isEmpty()) {
            insert newListReddit;
        }
        
        return newListReddit;
    
    }

    public static User generateUser(){

        Profile prof = [SELECT Id FROM Profile WHERE Name = 'Minimum Access - Salesforce'];

        User myUser = new User(FirstName = 'Test',
                                LastName = 'User',
                                Alias = 'tuser',
                                Email = 'jonas.junior.pinto@test.org',
                                Username = 'jonas.junior.pinto@test.org',
                                LanguageLocaleKey = 'en_US',
                                EmailEncodingKey = 'UTF-8',
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                ProfileId = prof.Id
        );

        insert myUser;
        return myUser;

    }

}